//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Web;
using System.Web.UI;

namespace PostJavaScript
{
public partial class Default : System.Web.UI.Page
{
string FuncCopyItem(string name, string source, string destiny)
{
    string s = "function " + name + "() {" +
" var control = document.getElementById(\"" + source + "\"); " +
" var controlSelected = document.getElementById(\"" + destiny + "\"); " +
"var selectedElements = 0; " +
"if (control.options.selectedIndex == -1)" +
" alert(\"lista vacia\"); " +
" else { " +
" var index = 0; " +
" if (controlSelected.options.length > 0) " +
" selectedElements = controlSelected.options.length;" +
" for (i = 0; i < control.length; i++) { " +
" if (control.options[i].selected == true) { " +
"controlSelected.options[selectedElements + index] = " +
"new Option(control.options[i].text, " +
"control.options[i].value); " +
" control.options[i] = null; " +
" index++;" +
" }" +
" } " +
" }" +
" } ";
    return s;
}
protected void Page_Load(object sender, EventArgs args)
{
    //creamos el script
    //en este ejemplo los controles ya han sido creados
    //por eso registramos los scripts al final del formulario ya que
    //usamos la propiedad ClientID
    //con el parámetro true ponemos las etiquetas de <script>
    string ddl_one = ddlAcceptedContacts.ClientID;
    string ddl_two = ddlRemovedContacts.ClientID;
    string sc1 = FuncCopyItem("addContact", ddl_one,ddl_two );
    string sc2 = FuncCopyItem("removeContact", ddl_two, ddl_one);
    ClientScriptManager cs = Page.ClientScript;
    cs.RegisterStartupScript(this.GetType(), "addContact", sc1, true);
    cs.RegisterStartupScript(this.GetType(), "removeContact", sc2, true);
}
}
}